### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by WesselKuipers** [pengx17/monaco-yaml#11]
`README.md` states that ESM support is added but not tested.

However, when looking at the latest release available on npm, the ESM-style files do not appear to be included.

What is the current status on supporting ESM? I'd love to be able to integrate this plugin into my React app in combination with webpack by implementing what the monaco-editor repository states for [integrating with webpack](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md), but without ESM support this does not appear to be an option.

**Comment by ad34** [comment]
I m trying to use it with vue monaco and webpack and I cannot make it working properly.

**Comment by ahmadmu** [comment]
We discussed it a bit in issue #3 , it's possible to load monaco and this library as AMD in ESM style files. Here is how @pengx17 added it to his project: https://github.com/alauda/ng-monaco-editor/blob/master/src/monaco-provider.service.ts#L160

Here is another example of how to load the library in Angular projects:
https://github.com/SamVerschueren/ngx-monaco/blob/master/src/services/monaco-editor.service.ts

**Comment by pengx17** [comment]
@WesselKuipers Sorry that I am not actively maintaining this repo any longer due to career change. I think you could still use what is already provided with AMD solution.

**Comment by yazaabed** [comment]
Is this still relevant after Monaco-yaml 2.5.1?

**Comment by WesselKuipers** [comment]
> Is this still relevant after Monaco-yaml 2.5.1?

I haven't tried since last time, but I'm still interested in getting this to work in the context I was trying to make it work in before.

I'll give it another go soon! 👍

**Comment by remcohaszing** [comment]
@WesselKuipers is my coworker and I know for a fact this is working in our project.
