### ISSUE TITLE
monaco-yaml with react-monaco-editor and webpack

### ISSUE THREAD

**Issue by humandad** [pengx17/monaco-yaml#12]
I'm trying to get monaco-yaml to work with react-monaco-editor and webpack. It looks like I got everything working, correctly and the yaml.worker is loading without errors. The only issue is that when I attempt to use any feature of monaco-yaml, it just never proceeds. Intellisense is stuck on "Loading...". From examining the code it looks like the MonacoWebWorkerImpl.prototype._getForeignProxy function in webworker.js never resolves or rejects, it just waits. Has anyone run into anything like this?

**Comment by pengx17** [comment]
Sorry I was off from this project for sometime. The current version might not work with the mainstream monaco-editor or webpack plugin. I might take sometime this month and get it synced.

**Comment by plusplusben** [comment]
Sounds good. I'm pretty new to both Monaco and Typescript, but I'd be glad to help with docs/testing/examples if that would be helpful.

**Comment by kristenmills** [comment]
I've gotten it working with react-monaco-editor and webpack and updated to the latest versions of yaml-language-server on a fork (https://github.com/kristenmills/monaco-yaml). It probably needs to be cleaned up before merging upstream (and probably added docs) but i'll make a pr at some point.

**Comment by pengx17** [comment]
@kristenmills Nice! I truly find no time this period to keep it with the upstream dependencies. I am looking forward for your PR 💃

**Comment by remorses** [comment]
Is there an usage example with react?

**Comment by kristenmills** [comment]
I can make a PR for a minimal working example with react, webpack, and react-monaco-editor.

**Comment by kristenmills** [comment]
@remorses hasn't been merged yet but you can see #18 for some react+webpack+react-monaco-editor examples.

**Comment by remorses** [comment]
@kristenmills thank you
