### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by pengx17** [pengx17/monaco-yaml#16]
Due to personal issues, I will not have time to continue maintaining this repo or npm package any longer. Leave comments if you are interested for being a maintainer.

**Comment by gautamits** [comment]
I would like to help. How can I help ?

**Comment by yazaabed** [comment]
I would like also to maintain and help. What is the pipeline for this ropo? And how we should start?

**Comment by vardanbansal-harness** [comment]
I'm interested to help.

**Comment by fleon** [comment]
I'm interested in maintainership as well. As a reference, I work at GitLab and have recently [integrated this library in GitLab's Web IDE](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/35838) for schema-based validation. We require this library to be maintained and up to date with the latest version of Monaco, so I am willing to contribute in that regard as required.

**Comment by pengx17** [comment]
@fleon I will add you as a maintainer. Could you also provide your npm id so I can get you npm publish permission as well?

**Comment by fleon** [comment]
Thanks @pengx17. My npm id is also [**fleon**](https://www.npmjs.com/~fleon).

**Comment by acao** [comment]
@yazaabed following up on your comment in another thread about being a maintainer, I would love to help y'all!  I maintain the graphql LSP and `monaco-graphql` full time, and we will be making full use of this language service soon for our in-browser IDE experience called `graphiql`.
we also plan on using the test suite here as a model for `monaco-graphql`'s test suite
let me know how I can help! glad to help review PRs, etc just ping me!

**Comment by remcohaszing** [comment]
Can I be a maintainer? I have been making pull requests lately, but everything appears to be stalled again.

**Comment by pengx17** [comment]
> Can I be a maintainer? I have been making pull requests lately and I’m interested in making sure this project stays up-to-date, but everything appears to be stalled again.

Since I no longer maintain this repo, it will be @yazaabed's call :)

**Comment by fleon** [comment]
I don't mind adding @remcohaszing as a maintainer. His recent MRs have been good contributions. (Though I myself have been not very active lately.)

@pengx17 Could you please add him as a maintainer in this repo and also on the NPM package? Thanks!

**Comment by remcohaszing** [comment]
@pengx17 thanks for adding me to the repository. Could you also add me as a maintainer on npm? My username on npm is also [`remcohaszing`](https://www.npmjs.com/~remcohaszing).

**Comment by pengx17** [comment]
@remcohaszing sorry for the wait. It looks like it keeps showing `Service Unavailable` error when I try to visit the package's setting page. I will try again soon.

**Comment by remcohaszing** [comment]
I can confirm I have maintainer access to the package on npm now. Thanks!

**Comment by pengx17** [comment]
> I can confirm I have maintainer access to the package on npm now. Thanks!

You are welcome! And thanks for maintaining this repo 😀
