### ISSUE TITLE
Remove yaml-language-server code from the repo

### ISSUE THREAD

**Issue by fleon** [pengx17/monaco-yaml#25]
I'm not sure why [`yaml-language-server`](https://github.com/redhat-developer/yaml-language-server)'s code has been copied into the repo. Maybe there are some custom code changes from the fork, but in that case, its quite unelegant to modify a third party dependency within the repo's source code. This makes it very difficult to maintain and upgrade dependencies.

So I propose we remove the sources of other repos included in this repo and reference them via dependencies. The repo sources included are:

- `yaml-language-server`
- `yaml-ast-parser-custom-tags` (which isn't really being imported/used anywhere and not used because [`js-yaml`](https://github.com/nodeca/js-yaml) is used instead.

If the repos mentioned above have custom modifications needed for this repo, we should fork them and reference those forks instead.

**Comment by fleon** [comment]
`yaml-ast-parser-custom-tags` is actually used by `yaml-language-server`, so by referencing `yaml-language-server` through `node_modules`, we can get rid of this code too in the repo.

**Comment by apisim** [comment]
Hello,

You may want to read [this](https://github.com/redhat-developer/yaml-language-server/issues/104). 

Then I'd suggest taking a look at this [monaco-yaml fork](https://github.com/apimastery/monaco-yaml) - it has successfully removed the embedded yaml-language-server and yaml-ast-parser-custom-tags.

There is a catch, though - you'll notice the dependency on a [yaml-language-server](https://github.com/apimastery/monaco-yaml/blob/master/package.json#L38) fork. The key change in that fork is in the added [scripts](https://github.com/apimastery/monaco-yaml/tree/master/scripts) and executing them at build time to create what's in the [esm folder](https://github.com/apimastery/monaco-yaml/tree/master/lib/esm)...plus few other fixes and enhancements, including in the formatter that uses `prettier`.

Our prototype was successful but we had to change priorities. So, we never got to submit a PR to redhat-developer/yaml-language-server to have the changes (eventually) incorporated. At this time, the fork has fallen a few commits behind.
