### ISSUE TITLE
Monaco-yaml bundle size has quintupled

### ISSUE THREAD

**Issue by patrickshipe** [pengx17/monaco-yaml#31]
I use `monaco-yaml` with the Monaco webpack plugin. After upgrading the `monaco-yaml` version a few days ago, the YAML worker size in the bundle has quintupled: 

**Before** `302.33 KB  build/static/js/yaml.worker.worker.be29fed70a279074a7221032a1be3734.js`
**After** `1.53 MB    build/static/js/yaml.worker.worker.be29fed70a279074a7221032a1be3734.js`

This also causes the build process to take considerably more memory. Any idea what may have caused this?

Thank you to everyone working to maintain this library - it's incredibly useful to us!

**Comment by yazaabed** [comment]
I think this is related to latest changes of removing the yaml-server from Monaco-yaml and made it as peer dependency check this PR here https://github.com/pengx17/monaco-yaml/pull/27.

**Comment by abeMedia** [comment]
I have a similar issue just way more extreme... The size of my worker has gone from 1MB to 8MB with the latest update.

**Comment by patrickshipe** [comment]
At least for me, the worker size has gone back to what it was before after: https://github.com/pengx17/monaco-yaml/pull/34

**Comment by yazaabed** [comment]
> At least for me, the worker size has gone back to what it was before after: #34

Yeah for me also after we merged 2.5.1 it went down to the normal size.

**Comment by yazaabed** [comment]
Can we close this issue?
