### ISSUE TITLE
yaml-worker 'exports is not defined' error

### ISSUE THREAD

**Issue by nwmac** [pengx17/monaco-yaml#32]
I'm trying to get the umd example working - I've built `monaco-yaml` using yarn.

It looks like the paths in `examples/umd` are out by a level, so I've copied `index.html` from the `examples/umd` folder to `examples`.

I can open `index.html` in a browser and the editor loads. I can see that the yaml functionality is working, apart from the auto-completion and anything that relies on the language server, looking at the console log, I see:

```
Uncaught ReferenceError: exports is not defined
    at yamlWorker.js:1548
```

Any help or pointers greatly appreciated.

**Comment by yazaabed** [comment]
Have you used loader.js from Monaco-editor before calling yamlWorker?

**Comment by nwmac** [comment]
I'm just trying to load the example that's in the `examples/umd` folder and I get the error above

**Comment by yazaabed** [comment]
Have you tried latest version 2.5.1?

**Comment by nwmac** [comment]
I did try the latest 2.5.1 and still had the same problem

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/109120872-79a0cd00-7781-11eb-9adb-6b9cb81b4696.png)

@yazaabed They are not wrapped into umd correctly, can you help to save us?

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/109121072-be2c6880-7781-11eb-8b54-7282a96886a2.png)

The `tsconfig` files should not be included in npm.

**Comment by remcohaszing** [comment]
I have removed the UMD bundle in v3.0.0 as it was broken and I believe the way forward for the npm ecosystem is to support ESM only. That having said, I would accept a PR to reimplement UMD and adds a working example.
