### ISSUE TITLE
Update Yaml Language Server to 0.11.0

### ISSUE THREAD

**Issue by apupier** [pengx17/monaco-yaml#33]
https://github.com/redhat-developer/yaml-language-server/blob/master/CHANGELOG.md#0110

**Comment by fleon** [comment]
Hi @apupier, the official support for UMD and ESM bundles sounds really good, and thanks for your upstream contribution. Do you mind creating a PR for this? Thanks!

cc @yazaabed

**Comment by apisim** [comment]
@apupier I still see on npmjs.com 0.10.1 as being the latest version of yaml-language-server...

Once 0.11.0 is published with the new ESM and UMD modules, I will create a PR to incorporate the changes from my [fork](https://github.com/apimastery/monaco-yaml) to start using those modules and fix some of the technical debt this project incurred when removing the embedded yaml-language-server and yaml-ast-parser-custom-tags code (e.g. [having to patch dependencies, broken formatting](https://github.com/pengx17/monaco-yaml/pull/30#issuecomment-677701309)).

Cheers!

**Comment by apupier** [comment]
@evidolob any ideas why the 0.11.0 version is not showing up on npm?

**Comment by evidolob** [comment]
@apupier because it not released, I have plan to release 0.11.0 today or tomorrow

**Comment by apupier** [comment]
> @apupier because it not released, I have plan to release 0.11.0 today or tomorrow

dumb of me. Sorry.

**Comment by yazaabed** [comment]
@apupier can we close this now?

**Comment by apupier** [comment]
seems yes. https://github.com/pengx17/monaco-yaml/blob/36e4f908e7248795754176e5eec709e7858345a2/package.json#L38

thanks!
