### ISSUE TITLE
Property 'yaml' does not exist on type 'typeof languages'

### ISSUE THREAD

**Issue by mraimon** [pengx17/monaco-yaml#37]
i'm using `ngx-monaco-editor` (https://github.com/atularen/ngx-monaco-editor#readme) library in my Angular project. also i would like to use `monaco-yaml`: 

`monaco.languages.yaml.yamlDefaults.setDiagnosticsOptions({ ... })`

for some reason i get following error:

`error TS2339: Property 'yaml' does not exist on type 'typeof languages'.`

i cannot understand, what's the problem: `ngx-monaco-editor` already contains `monaco-editor` lib, and `monaco.languages` is defined, but there is no `yaml` property. that's kinda strange for me, since in `monaco-yaml` is declared same `monaco` namespace with property `yaml`, so it's global scope, but my code see only `monaco` namespase properties defined in `ngx-monaco-editor`

i'll be happy if anyone has any ideas about what could that be

**Comment by yazaabed** [comment]
I have the same issue. I am not sure why typescript can't find the Monaco.d.ts. Can you for now ignore that by // @ts-ignore until we find a solution for this.
