### ISSUE TITLE
`monaco-yaml/lib/esm/languageFeatures.js` is readling global `monaco` which is not available

### ISSUE THREAD

**Issue by JounQin** [pengx17/monaco-yaml#44]
As title, when using esm version, no global `monaco` will be available

v2.5.1

**Comment by shabalin** [comment]
The provided examples stop working if you bump version of react-monaco-editor to 0.35.0 or higher.

**Comment by JounQin** [comment]
Workaround from `monaco-editor-webpack-plugin`: `globalAPI` option.

See also: https://github.com/microsoft/monaco-editor-webpack-plugin#options
