### ISSUE TITLE
Is `completion` or `hover` option available in `DiagnosticsOptions`?

### ISSUE THREAD

**Issue by JounQin** [pengx17/monaco-yaml#51]
In the type definition file, they are not available:

https://github.com/pengx17/monaco-yaml/blob/master/src/monaco.d.ts#L7-L45

But they are used in demos: https://github.com/pengx17/monaco-yaml/search?q=completion

And according to the doc:

> * Code completion, based on JSON schemas or by looking at similar objects in the same file
> * Hovers, based on JSON schemas

So, my question is are the two feature not configurable? Or should they be added into the type definition file?

**Comment by remcohaszing** [comment]
I added this in #60. This has been released in version 3.0.0.
