### ISSUE TITLE
Schema not working

### ISSUE THREAD

**Issue by ahmadmu** [pengx17/monaco-yaml#7]
I enabled quickSuggestions for the editor, and in the console the yaml schemas array has my schema object , but the schema is not working. I'm using this tool to generate the schema https://www.jsonschema.net/ from my original json file to test it, and I also tried using a js object schema, neither works. fileMatch and the uri has the name of my content uri. Do you know if I need to configure something else to get it to work?

**Comment by pengx17** [comment]
The demo included in this repo's test folder should be a working configuration with a Kubernetes deployment schema. Have you tried it yet?
Could you please for this repo and modify the test and let me see if you configured correctly?

**Comment by ahmadmu** [comment]
The Kubernetes schema in the test folder got deprecated apparently. They do suggest a new schema but I can't get it to work. You normally press ctrl/cmd + space to show the suggestions, right? Pressing them when the editor is empty just shows "no suggestions".

**Comment by pengx17** [comment]
The schema was deprecated but should work any way.
Suggestion aka auto complete may not work properly at the moment. Other than that, validation and hover should work.
I am currently working on fixing auto complete feature. Please wait for a week or so.

**Comment by yazaabed** [comment]
Closing this as it is 2 years already and we changed a lot in the mean while.
